#for test locally

management:
  endpoints:
    web:
      exposure:
        include: prometheus, metrics
  metrics:
    enable:
      jvm: true
      hikaricp: true
      process: true
      logback: false
      tomcat: false
      system: true
      jdbc: false
      http: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/process_engine
    username: postgres
    password: admin

camunda:
  bpm:
    history-level: none

